[package]
name = "datto_gis"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui_http_client = "0.2.2"
reqwest = { version = "0.13.4", features = ["blocking"] }
anyhow = "1.0.104"
futures = "0.3.33"
http = "1.0"
url = "2.5"
proj-core = "0.9.0"
duckdb = { version = "1.10505.0", features = ["bundled"] }